import Database from 'better-sqlite3'; import fs from 'node:fs'; import path from 'node:path';
const databasePath = path.join(process.cwd(), 'data', 'flytloop.db'); let connection: Database.Database | undefined;
export function db() { if (connection) return connection; fs.mkdirSync(path.dirname(databasePath), { recursive: true }); connection = new Database(databasePath); connection.pragma('journal_mode = WAL'); connection.pragma('foreign_keys = ON'); initialize(connection); return connection; }
function initialize(d: Database.Database) { d.exec(`
CREATE TABLE IF NOT EXISTS accounts (id TEXT PRIMARY KEY, name TEXT NOT NULL, normalized_name TEXT UNIQUE NOT NULL, industry TEXT, region TEXT, tier TEXT, health TEXT, arr REAL DEFAULT 0, owner TEXT, source_file TEXT NOT NULL, source_imported_at TEXT NOT NULL, source_checksum TEXT, source_removed INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS devices (id INTEGER PRIMARY KEY AUTOINCREMENT, account_id TEXT NOT NULL REFERENCES accounts(id), name TEXT NOT NULL, UNIQUE(account_id,name));
CREATE TABLE IF NOT EXISTS source_feature_requests (source_key TEXT PRIMARY KEY, title TEXT NOT NULL, product_area TEXT, source_status TEXT, mentions INTEGER, revenue REAL, source_file TEXT, source_imported_at TEXT, source_checksum TEXT, source_removed INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS source_feature_accounts (source_key TEXT REFERENCES source_feature_requests(source_key), account_id TEXT REFERENCES accounts(id), PRIMARY KEY(source_key,account_id));
CREATE TABLE IF NOT EXISTS source_issues (source_id TEXT PRIMARY KEY, account_id TEXT REFERENCES accounts(id), source_category TEXT, source_status TEXT, title TEXT, normalized_title TEXT, canonical_type TEXT, source_file TEXT, source_imported_at TEXT, source_checksum TEXT, source_removed INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS meeting_notes (source_id TEXT PRIMARY KEY, account_id TEXT REFERENCES accounts(id), topic TEXT, attendees_json TEXT, date TEXT, source_file TEXT, source_imported_at TEXT, source_checksum TEXT, source_removed INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS meeting_action_items (id INTEGER PRIMARY KEY AUTOINCREMENT, meeting_id TEXT REFERENCES meeting_notes(source_id), position INTEGER, text TEXT, UNIQUE(meeting_id,position));
CREATE TABLE IF NOT EXISTS source_tasks (source_id TEXT PRIMARY KEY, account_id TEXT REFERENCES accounts(id), title TEXT, assignee TEXT, priority TEXT, source_status TEXT, due TEXT, source_file TEXT, source_imported_at TEXT, source_checksum TEXT, source_removed INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS feedback_items (id TEXT PRIMARY KEY, source_key TEXT UNIQUE, type TEXT NOT NULL, title TEXT NOT NULL, summary TEXT, product_area TEXT DEFAULT 'other', priority TEXT DEFAULT 'MEDIUM', stage TEXT NOT NULL, owner_team TEXT, source_status TEXT, source_category TEXT, mentions INTEGER DEFAULT 0, revenue REAL DEFAULT 0, origin TEXT NOT NULL, parent_id TEXT REFERENCES feedback_items(id), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, source_imported_at TEXT, source_removed INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS feedback_accounts (feedback_id TEXT REFERENCES feedback_items(id), account_id TEXT REFERENCES accounts(id), PRIMARY KEY(feedback_id,account_id));
CREATE TABLE IF NOT EXISTS feedback_source_links (feedback_id TEXT REFERENCES feedback_items(id), source_type TEXT, source_id TEXT, PRIMARY KEY(feedback_id,source_type,source_id));
CREATE TABLE IF NOT EXISTS feedback_stage_history (id INTEGER PRIMARY KEY AUTOINCREMENT, feedback_id TEXT REFERENCES feedback_items(id), from_stage TEXT, to_stage TEXT NOT NULL, note TEXT, actor TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS feedback_comments (id INTEGER PRIMARY KEY AUTOINCREMENT, feedback_id TEXT REFERENCES feedback_items(id), body TEXT NOT NULL, author TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS feedback_relationships (id INTEGER PRIMARY KEY AUTOINCREMENT, parent_id TEXT REFERENCES feedback_items(id), child_id TEXT REFERENCES feedback_items(id), relation_type TEXT NOT NULL, created_at TEXT NOT NULL, UNIQUE(parent_id,child_id,relation_type));
CREATE TABLE IF NOT EXISTS customer_validations (id INTEGER PRIMARY KEY AUTOINCREMENT, feedback_id TEXT REFERENCES feedback_items(id), account_id TEXT REFERENCES accounts(id), demo_given INTEGER DEFAULT 0, demo_date TEXT, customer_tried TEXT DEFAULT 'NOT_YET', customer_tried_date TEXT, reaction TEXT, updated_at TEXT NOT NULL, UNIQUE(feedback_id,account_id));
CREATE TABLE IF NOT EXISTS customer_feedback (id INTEGER PRIMARY KEY AUTOINCREMENT, feedback_id TEXT REFERENCES feedback_items(id), account_id TEXT REFERENCES accounts(id), text TEXT NOT NULL, sentiment TEXT, analysis_json TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS notifications (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, body TEXT NOT NULL, read_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS activity_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, action TEXT NOT NULL, detail TEXT, actor TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS dataset_imports (id INTEGER PRIMARY KEY AUTOINCREMENT, file_name TEXT NOT NULL, checksum TEXT NOT NULL, record_count INTEGER NOT NULL, warnings_json TEXT NOT NULL, errors_json TEXT NOT NULL, imported_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ai_executions (id INTEGER PRIMARY KEY AUTOINCREMENT, agent_type TEXT NOT NULL, input_reference TEXT, model TEXT, status TEXT NOT NULL, duration_ms INTEGER, output_json TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS ai_suggestions (id INTEGER PRIMARY KEY AUTOINCREMENT, execution_id INTEGER REFERENCES ai_executions(id), feedback_id TEXT REFERENCES feedback_items(id), suggestion_type TEXT, payload_json TEXT NOT NULL, approved_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS subscriptions (id INTEGER PRIMARY KEY AUTOINCREMENT, feedback_id TEXT REFERENCES feedback_items(id), user_id TEXT, created_at TEXT NOT NULL, UNIQUE(feedback_id,user_id));
CREATE TABLE IF NOT EXISTS integration_connections (id INTEGER PRIMARY KEY AUTOINCREMENT, provider TEXT UNIQUE, status TEXT NOT NULL, detail TEXT, checked_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, name TEXT NOT NULL, role TEXT NOT NULL); CREATE TABLE IF NOT EXISTS team_memberships (id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT REFERENCES users(id),team TEXT NOT NULL, UNIQUE(user_id,team));
`); d.prepare(`INSERT OR IGNORE INTO users(id,name,role) VALUES ('demo-solutions','Demo Solutions User','SOLUTIONS'),('demo-product','Demo Product User','PRODUCT'),('demo-engineering','Demo Engineering User','ENGINEERING')`).run(); }
export const now = () => new Date().toISOString();
export const makeId = (prefix:string, index:number) => `${prefix}-${String(index).padStart(3,'0')}`;
export const nextFeedbackId = (type:string) => { const prefix=type==='BUG'?'BUG':type==='SUPPORT'?'SUP':'FR'; const count=(db().prepare(`SELECT COUNT(*) AS count FROM feedback_items WHERE id LIKE ?`).get(`${prefix}-%`) as {count:number}).count; return makeId(prefix,count+1); };
export function audit(entityType:string, entityId:string, action:string, detail:string, actor='Demo User'){db().prepare('INSERT INTO activity_logs(entity_type,entity_id,action,detail,actor,created_at) VALUES (?,?,?,?,?,?)').run(entityType,entityId,action,detail,actor,now())}
export function notify(title:string, body:string){db().prepare('INSERT INTO notifications(title,body,created_at) VALUES (?,?,?)').run(title,body,now())}
